apiVersion: v1
kind: Pod
metadata:
  name: fortio-client
  namespace: microservices-demo
  annotations:
    sidecar.istio.io/inject: "false"  # Disable Istio sidecar injection
spec:
  containers:
  - name: fortio
    image: fortio/fortio:latest
    command: ["sleep", "3600"]