apiVersion: v1
kind: Pod
metadata:
  name: test-client
  namespace: microservices-demo
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ['sh', '-c', 'while true; do sleep 3600; done']