apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: microservices-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: docker.io/satish2024/product-service:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: microservices-demo
spec:
  selector:
    app: product-service
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP